============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/stidsem4/iut/2021/controle/andrea.masse/c16_03
collected 7 items

test_16_03.py F......                                                    [100%]

=================================== FAILURES ===================================
_____________________________ Test1603sute.test_10 _____________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_10>

    def test_10(self):
        try:
            from .main  import Note
        except:
           assert False
        try:
            Note.vider()
        except:
            assert False
        note1 = Note('elv1', 'xx', 12)
        note1 = Note('elv1', 'yy', 13)
        note1 = Note('elv1', 'yy', 14)
        note1 = Note('elv2', 'zz', 13)
        try:
>           assert Note.moyenne('elv1') == 13
E           TypeError: moyenne() takes 1 positional argument but 2 were given

test_16_03.py:106: TypeError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_10>

    def test_10(self):
        try:
            from .main  import Note
        except:
           assert False
        try:
            Note.vider()
        except:
            assert False
        note1 = Note('elv1', 'xx', 12)
        note1 = Note('elv1', 'yy', 13)
        note1 = Note('elv1', 'yy', 14)
        note1 = Note('elv2', 'zz', 13)
        try:
            assert Note.moyenne('elv1') == 13
    
            assert Note.moyenne('elv1', 'yy') == 13.5
        except TypeError as err:
            if 'argument' in err.args[0]:
>               assert False, 'Probleme de parametres'
E               AssertionError: Probleme de parametres
E               assert False

test_16_03.py:111: AssertionError
----------------------------- Captured stdout call -----------------------------
-- Question 4 a) --
[('eleve1', 'math', 13), ('eleve1', 'physique', 15), ('eleve1', 'math', 13), ('eleve1', 'eco', 12), ('eleve1', 'eco', 13), ('eleve1', 'math', 12)]
13.0
-- Question 4 b) --
[('eleve1', 'math', 13), ('eleve1', 'math', 13), ('eleve1', 'math', 12)]
12.666666666666666
-- Question 4 c) --
12.666666666666666
13.125
12.666666666666666
-- Question 5 --
eleve1
maths
13
eleve eleve1 matiere maths note 13
eleve eleve1 matiere maths note 13
[<c16_03.main.Note object at 0x7f9fab9862e0>, <c16_03.main.Note object at 0x7f9fab986130>, <c16_03.main.Note object at 0x7f9fab986100>, <c16_03.main.Note object at 0x7f9fab9861f0>, <c16_03.main.Note object at 0x7f9fab9861c0>, <c16_03.main.Note object at 0x7f9fab986220>, <c16_03.main.Note object at 0x7f9fab9865b0>, <c16_03.main.Note object at 0x7f9fab986490>]
--
<c16_03.main.Note object at 0x7f9fab9862e0>
<c16_03.main.Note object at 0x7f9fab986130>
<c16_03.main.Note object at 0x7f9fab986100>
<c16_03.main.Note object at 0x7f9fab9861f0>
<c16_03.main.Note object at 0x7f9fab9861c0>
<c16_03.main.Note object at 0x7f9fab986220>
<c16_03.main.Note object at 0x7f9fab9865b0>
<c16_03.main.Note object at 0x7f9fab986490>
eleve eleve1 matiere math note 13
eleve eleve1 matiere physique note 15
eleve eleve1 matiere math note 13
eleve eleve1 matiere eco note 12
eleve eleve1 matiere eco note 13
eleve eleve1 matiere math note 12
eleve eleve2 matiere math note 13
eleve eleve2 matiere math note 14
-- Question 6 --
eleve1
maths
13
Note('eleve1','maths','13')
-- Question 7 --
[]
Note('eleve1','math','13')
[<c16_03.main.Note object at 0x7f9fab986520>]
-- Question 8 --
13.125
12.666666666666666
-- Question 9 --
1
2
defaut
defaut
defaut
23
23
23
-1
23
14
-1
14
0
8
-- Question 10 --
0
8
0
Moyenne :
13.125
Moyenne avec moyennebis : 
13.125
Moyenne eleve1 en maths :
12.666666666666666
Moyenne en maths :
13.0
=========================== short test summary info ============================
FAILED test_16_03.py::Test1603sute::test_10 - AssertionError: Probleme de par...
========================= 1 failed, 6 passed in 0.06s ==========================
